#!/bin/sh

echo "Waiting for MySQL..."

while ! mysqladmin ping -h "$DATABASE_HOST" --silent --skip-ssl > /dev/null 2> /dev/null; do
    sleep 1;
done

echo "MYSQL started."

flask db upgrade

exec "$@"
