volumes:
  local_db_data: {}
  app_data: {}

networks:
  jtd_net:
    ipam:
      config:
        - subnet: "10.0.34.0/24"

services:
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./deploy/db/.env
    networks:
      jtd_net:
        ipv4_address: 10.0.34.2
    ports:
      - "3306:3306"
    volumes:
      - local_db_data:/var/lib/mysql

  app-server:
    build:
      context: .
      dockerfile: ./deploy/server/Dockerfile
    env_file:
      - ./deploy/server/.env
      - ./deploy/server/azure.env  # this is not committed
      - ./deploy/db/.env
    networks:
      jtd_net:
        ipv4_address: 10.0.34.3
    volumes:
      - ./:/app
      - app_data:/data
    depends_on:
      - db

  app-web:
    build:
      context: .
      dockerfile: ./deploy/web/Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_HOST: db
    networks:
      jtd_net:
        ipv4_address: 10.0.34.4
    depends_on:
      - db
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - app_data:/data

  lb:
    image: nginx
    networks:
      jtd_net:
        ipv4_address: 10.0.34.5
    volumes:
      - ./deploy/lb/conf/jtd.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-server
      - app-web
    ports:
      - "80:80"
